name: Update cpanfile.snapshot
on:
    schedule:
        - cron: "*/30 * * * *"
    workflow_dispatch:
jobs:
    update-dep:
        runs-on: "ubuntu-20.04"
        container:
            image: perl:5.36
        steps:
            - uses: actions/checkout@v2
            - name: Install Carton
              run: >
                  curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl -
                  install -g Carton
                  --show-build-log-on-failure
            - name: Install deps
              run: >
                  curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl -
                  install
                  --cpanfile cpanfile
                  --resolver metacpan
                  --show-build-log-on-failure
                  --local-lib-contained=local
            - name: Maybe update cpanfile.snapshot
              run: carton
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                  commit-message: Update cpanfile.snapshot
                  title: Update cpanfile.snapshot
                  body: |
                      Auto-generated by [create-pull-request][1]

                      [1]: https://github.com/peter-evans/create-pull-request
                  branch: update-cpanfile-snapshot
